name: CI

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '23 5 * * 2'  # weekly run to check things are still working

env:
  PYTHON_VERSION: 3.11

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: poetry

      - name: Install Dependencies using Poetry
        run: poetry install --extras dev

      - name: Check code
        run: poetry run pre-commit run --all

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: 'rucio/rucio'
          ref: '41.0.0'
          path: '.rucio'
          persist-credentials: false

      - name: Expose Rucio and XrootD service
        run: |
          cd "$GITHUB_WORKSPACE/.rucio"
          git apply "$GITHUB_WORKSPACE/ci/rucio/expose_ports.patch"
          echo "127.0.0.1	xrd1" | sudo tee -a /etc/hosts

      - name: Run docker compose
        uses: hoverkraft-tech/compose-action@11beaa1c2dae4e8ed7b1665aa074723b6cecb0e4  # v3.0.0
        with:
          compose-file: "${{ github.workspace }}/.rucio/etc/docker/dev/docker-compose.yml"
          compose-flags: "--profile storage"

      - name: Configure Rucio and populate with test data.
        shell: bash
        # Copied from https://github.com/rucio/rucio/blob/1bda46db14ae8be01198e4e55f98c70b9edeffed/.github/workflows/integration_tests.yml#L141
        run: |
          docker exec -t dev-rucio-1 bash -c "
            set -e
            cd /rucio_source
            pip install --no-cache-dir -e /rucio_source
            tools/run_tests.sh -ir
          "

      - name: Copy certificates
        run: |
          sudo mkdir /etc/grid-security
          sudo docker cp dev-rucio-1:/etc/grid-security/certificates /etc/grid-security
          docker cp dev-rucio-1:/tmp/x509up_u0 /tmp

      - name: Install XrootD client
        run: |
          sudo apt-get update
          sudo apt-get install xrootd-client

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install poetry
        run: pip install poetry

      - name: Determine dependencies
        run: poetry lock

      - name: Install dependencies
        run: poetry install --extras dev

      - name: Check Rucio and XrootD service availability
        run: |
          set -x
          poetry run rucio --verbose ping
          poetry run rucio whoami
          poetry run rucio did list test:* --filter type=file
          poetry run rucio replica list file test:file1
          poetry run rucio download test:file1
        env:
          RUCIO_CONFIG: "ci/rucio/rucio.cfg"
          X509_CERT_DIR: "/etc/grid-security/certificates"
          X509_USER_PROXY: "/tmp/x509up_u0"

      - name: Run tests
        run: >-
          poetry run pytest
          --log-level debug
          --cov
          --cov-branch
          --cov-report=xml
          --junitxml=junit.xml
          -o junit_family=legacy
        env:
          RUCIO_CONFIG: "ci/rucio/rucio.cfg"
          X509_CERT_DIR: "/etc/grid-security/certificates"
          X509_USER_PROXY: "/tmp/x509up_u0"

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3  # v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f  # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
